version: '3.8'

services:
  # Main Foundry development container
  foundry:
    build: .
    container_name: smart-order-router
    volumes:
      - .:/app
      - foundry_cache:/root/.foundry
    working_dir: /app
    environment:
      - FOUNDRY_PROFILE=default
    command: forge test --watch

  # Local Anvil node for testing
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: sor-anvil
    environment:
      ANVIL_IP_ADDR: "0.0.0.0"
    ports:
      - "8545:8545"
    command: anvil --host 0.0.0.0 --chain-id 1337

  # Smart contract deployment service
  deployer:
    build:
      context: .
      target: deployer
    container_name: sor-deployer
    environment:
      - RPC_URL=${RPC_URL}
      - PRIVATE_KEY=${PRIVATE_KEY}
    volumes:
      - ./broadcast:/app/broadcast
    depends_on:
      - anvil

volumes:
  foundry_cache:
