[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "tests/contracts"
cache_path = "cache_forge"
broadcast = "broadcast"
ffi = false
fs_permissions = [{ access = "read-write", path = "./" }]

solc = "0.8.19"
auto_detect_solc = false
optimizer = true
optimizer_runs = 200
viaIR = true

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "contracts/=contracts/",
    "tests/=tests/"
]

gas_reports = ["*"]
gas_reports_ignore = ["tests/**/*"]

[rpc_endpoints]
hyperliquid = "https://rpc.hyperliquid.xyz/evm"
localhost = "http://127.0.0.1:8545"
anvil = "http://127.0.0.1:8545"

[etherscan]
hyperliquid = { key = "${HYPERLIQUID_EXPLORER_API_KEY}", url = "https://explorer.hyperliquid.xyz/api" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"

[doc]
out = "docs"
title = "Hyperliquid Smart Order Router"
ignore = ["tests/**/*", "script/**/*"]

[profile.test]
src = "contracts"
test = "tests/contracts"
gas_limit = "18446744073709551615"
gas_price = 0

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000, depth = 1000 }

[profile.local]
optimizer = false
verbosity = 3
